### PR TITLE
Functionality

### PR DESCRIPTION
**Pull request by ylverhoog**
tekst

### CODE REVIEW

**Comment by berndkr** [comment]
Staat nog niet in de juiste volgorde in het verlsag, volgorde volgens blackboard:
1. Introduction, including a brief problem description and end-user's requirements
2. Overview of the developed and implemented software product
3. Reflection on the product and process from a software engineering perspective
4. Description of the developed functionalities
5. Special section on interaction design (development of the HCI module)
6. Evaluation of the functional modules and the product in its entirety, including the
failure analysis
7. Outlook

**Comment by ylverhoog** [comment]
ok op de goede plek gezet.

**Comment by mspanoghe** [comment]
Ik vraag mij alleen af hoe nuttig al die info is over hoe die emotionConfig werkt. Die info staat al in de docu van EmotionConfig.

**Comment by mspanoghe** [comment]
Wel goed!

**Pull request merged**
